# Generated by Django 5.0.4 on 2024-04-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_medicine_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('name', models.CharField(max_length=100)), 
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
             ],
        ),
       
    ]